backend:
  branch: main
  name: git-gateway
collections:
- create: true
  fields:
  - label: Title
    name: title
    widget: string
  - label: Publish Date
    name: date
    widget: datetime
  - label: Intro Blurb
    name: description
    widget: text
  - label: Image
    name: image
    required: false
    widget: image
  - label: Body
    name: body
    widget: markdown
  - collection: categories
    default: []
    display_fields:
    - title
    label: Categorias
    name: categories
    search_fields:
    - title
    value_field: title
    widget: relation
  - collection: tags
    default: []
    display_fields:
    - title
    label: Tags
    name: tags
    required: false
    search_fields:
    - title
    value_field: title
    widget: relation
  - label: SEO Title
    name: seo_title
    required: false
    widget: string
  - label: SEO Description
    name: seo_description
    required: false
    widget: text
  folder: site/content/post
  label: Artigos
  name: post
  path: '{{slug}}/index'
- files:
  - fields:
    - label: Title
      name: title
      widget: string
    - label: Subtitle
      name: subtitle
      widget: string
    - label: Image
      name: image
      widget: image
    - fields:
      - label: Heading
        name: heading
        widget: string
      - label: Text
        name: text
        widget: text
      label: Blurb
      name: blurb
      widget: object
    - fields:
      - label: Heading
        name: heading
        widget: string
      - label: Text
        name: text
        widget: text
      label: Intro
      name: intro
      widget: object
    - fields:
      - label: Image
        name: image
        widget: image
      - label: Text
        name: text
        widget: text
      label: Products
      name: products
      widget: list
    - fields:
      - label: Heading
        name: heading
        widget: string
      - label: Text
        name: text
        widget: text
      label: Values
      name: values
      widget: object
    file: site/content/_index.md
    label: Home Page
    name: home
  - fields:
    - label: Title
      name: title
      widget: string
    - label: Logo
      name: logo
      widget: image
    - label: Body
      name: body
      widget: markdown
    - fields:
      - label: Heading
        name: heading
        widget: string
      - label: Text
        name: text
        widget: text
      label: Contact Entries
      name: contact_entries
      widget: list
    file: site/content/contact/_index.md
    label: Contact Page
    name: contact
  - fields:
    - label: Title
      name: title
      widget: string
    - label: Image
      name: image
      widget: image
    - fields:
      - label: Heading
        name: heading
        widget: string
      - label: Description
        name: description
        widget: text
      - fields:
        - label: Image
          name: image
          widget: image
        - label: Text
          name: text
          widget: text
        label: Blurbs
        name: blurbs
        widget: list
      label: Intro
      name: intro
      widget: object
    - fields:
      - label: Heading
        name: heading
        widget: string
      - label: Description
        name: description
        widget: text
      - fields:
        - label: Image
          name: image
          widget: image
        - label: Alt
          name: alt
          widget: string
        label: Image1
        name: image1
        widget: object
      - fields:
        - label: Image
          name: image
          widget: image
        - label: Alt
          name: alt
          widget: string
        label: Image2
        name: image2
        widget: object
      - fields:
        - label: Image
          name: image
          widget: image
        - label: Alt
          name: alt
          widget: string
        label: Image3
        name: image3
        widget: object
      label: Main
      name: main
      widget: object
    - fields:
      - label: Quote
        name: quote
        widget: string
      - label: Author
        name: author
        widget: string
      label: Testimonials
      name: testimonials
      widget: list
    - label: Full_image
      name: full_image
      widget: image
    - fields:
      - label: Heading
        name: heading
        widget: string
      - label: Description
        name: description
        widget: string
      - fields:
        - label: Plan
          name: plan
          widget: string
        - label: Price
          name: price
          widget: string
        - label: Description
          name: description
          widget: string
        - label: Items
          name: items
          widget: list
        label: Plans
        name: plans
        widget: list
      label: Pricing
      name: pricing
      widget: object
    file: site/content/products/_index.md
    label: Products Page
    name: products
  - fields:
    - label: Title
      name: title
      widget: string
    - label: Image
      name: image
      widget: image
    - fields:
      - label: Heading
        name: heading
        widget: string
      - label: Text
        name: text
        widget: text
      - label: Image
        name: imageUrl
        widget: image
      label: Values
      name: values
      widget: list
    file: site/content/values/_index.md
    label: Values Page
    name: values
  label: Páginas
  name: pages
- files:
  - fields:
    - label: Title
      name: title
      widget: string
    - label: Blurb
      name: blurb
      widget: text
    file: site/data/footer.json
    label: Footer
    name: footer
  - editor:
      preview: false
    fields:
    - label: Site Title for Browser Tab
      name: title
      widget: string
    - fields:
      - field:
          label: Image
          name: image
          widget: image
        label: Open Graph Image
        name: images
        widget: list
      label: Params
      name: params
      widget: object
    file: site/hugo.toml
    label: Hugo Config
    name: config
  label: Configurações do Site
  name: site_settings
- create: true
  fields:
  - label: Título
    name: title
    widget: string
  - label: Slug
    name: slug
    widget: string
  - label: Descrição
    name: description
    required: false
    widget: text
  folder: site/content/categories
  label: Categorias
  name: categories
- create: true
  fields:
  - label: Título
    name: title
    widget: string
  - label: Slug
    name: slug
    widget: string
  folder: site/content/tags
  label: Tags
  name: tags
media_folder: site/static/img
public_folder: img
