backend:
  name: git-gateway
  branch: main

media_folder: "site/static/img" # Folder where user uploaded files should go
public_folder: "img"

collections:
  - name: "categories"
    label: "Categorias"
    folder: "site/content/categories"
    create: true
    fields:
      - {label: "Nome", name: "name", widget: "string"}
      - {label: "Descrição", name: "description", widget: "text"}

  - name: "tags"
    label: "Tags"
    folder: "site/content/tags"
    create: true
    fields:
      - {label: "Nome", name: "name", widget: "string"}
      - {label: "Descrição", name: "description", widget: "text"}

  - name: "post"
    label: "Artigos"
    folder: "site/content/post"
    path: "{{slug}}/index"
    create: true
    fields:
      - {label: "Título", name: "title", widget: "string"}
      - {label: "Data de Publicação", name: "date", widget: "datetime"}
      - {label: "Resumo", name: "description", widget: "text"}
      - {label: "Imagem de Destaque", name: "image", widget: "image", required: false}
      - {label: "Categorias", name: "categories", widget: "relation", collection: "categories", searchFields: ["name"], valueField: "name", multiple: true}
      - {label: "Tags", name: "tags", widget: "relation", collection: "tags", searchFields: ["name"], valueField: "name", multiple: true}
      - {label: "Conteúdo", name: "body", widget: "markdown"}

  - name: "pages"
    label: "Páginas"
    files:
      - file: "site/content/_index.md"
        label: "Página Inicial"
        name: "home"
        fields:
          - {label: "Título", name: "title", widget: "string"}
          - {label: "Subtítulo", name: "subtitle", widget: "string"}
          - {label: "Imagem", name: "image", widget: "image"}
          - {label: "Bloco Inicial", name: "blurb", widget: "object", fields: [
              {label: "Cabeçalho", name: "heading", widget: "string"},
              {label: "Texto", name: "text", widget: "text"}]}
          - {label: "Introdução", name: "intro", widget: "object", fields: [
              {label: "Cabeçalho", name: "heading", widget: "string"},
              {label: "Texto", name: "text", widget: "text"}]}
      - file: "site/content/contact/_index.md"
        label: "Página de Contato"
        name: "contact"
        fields:
          - {label: "Título", name: "title", widget: "string"}
          - {label: "Logo", name: "logo", widget: "image"}
          - {label: "Conteúdo", name: "body", widget: "markdown"}
          - label: "Entradas de Contato"
            name: "contact_entries"
            widget: "list"
            fields:
              - {label: "Cabeçalho", name: "heading", widget: "string"}
              - {label: "Texto", name: "text", widget: "text"}

  - name: "site_settings"
    label: "Configurações do Site"
    files:
      - file: "site/data/footer.json"
        label: "Rodapé"
        name: "footer"
        fields:
          - {label: "Título", name: "title", widget: "string"}
          - {label: "Descrição", name: "blurb", widget: "text"}
      - file: "site/hugo.toml"
        label: "Configuração Hugo"
        name: "config"
        editor:
          preview: false
        fields:
          - {label: "Título do Site (Aba do Navegador)", name: "title", widget: "string"}
          - label: "Parâmetros"
            name: "params"
            widget: "object"
            fields:
              - label: "Imagem Open Graph"
                name: "images"
                widget: "list"
                field: {label: "Imagem", name: "image", widget: "image"}
