backend:
  name: git-gateway
  branch: main

media_folder: "static/uploads"
public_folder: "/uploads"

collections:
  - name: "test"
    label: "Test Collection"
    folder: "content/test"
    create: true
    fields:
      - { name: "title", label: "Title", widget: "string" }
